<li class="{dede:field.currentstyle/}"><a class="first-level" href="{dede:field name='typeurl'/}" target=""><strong>{dede:field name='typename'/}</strong></a><i></i>
                <ul class="">
                  {dede:channel type='son' noself='yes'}
                  <li class=""><a class="" href="[field:typelink/]" target=""><strong>[field:typename/]</strong></a></li>
                  {/dede:channel}
                </ul>
              </li>