
<field:en_subject itemname="subject" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:en_subject>

<field:en_name itemname="name" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:en_name>

<field:en_email itemname="email" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:en_email>

<field:en_tel itemname="tel" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:en_tel>

<field:en_content itemname="content" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:en_content>
