<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",18,95);
$z[0][4]['runphp']="yes";
$z[1]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",116,201);
$z[1][4]['runphp']="yes";
$z[2]=Array("imgsrc","",232,247);
$z[3]=Array("imgwidth","",261,279);
$z[4]=Array("alttext","",285,302);
$z[5]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",402,482);
$z[5][4]['runphp']="yes";

?>