<li class="not-animated" data-animate="fadeInUp" data-delay="200">
                                  <div class="portfolio-img"><a href="[field:arcurl/]"  title="[field:title/]"><img src="[field:picname/]" alt="[field:title/]" /><span class="opacity-overlay"></span><i class="icon-video"></i></a></div>
                                  <div class="portfolio-title">
                                    <h2><a href="[field:arcurl/]"  title="[field:title/]">[field:title/]</a></h2>
                                  </div>
                                </li>