<li class="headlines-content"><!-- S entry-item -->
                                  <div class="entry-item">
                                    <div class="typo">
                                      <div class="typo-img">
                                        <div class="entry-img"><a href="[field:arcurl/]" target="_blank"><img src="[field:picname/]" width="160" alt="[field:title/]" /></a></div>
                                      </div>
                                      <!-- end of typo-img -->
                                      <div class="typo-text">
                                        <div class="entry-title">
                                          <h2><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h2>
                                        </div>
                                        <div class="entry-summary">
                                          <div class="qhd-content">
                                            <p> [field:description function="cn_substr(@me,180)"/]...</p>
                                          </div>
                                        </div>
                                      </div>
                                      <!-- end of typo-text --></div>
                                  </div>
                                  <!-- E entry-item --></li>