<?php
$z[0]=Array("global","",105,132);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",164,191);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",304,331);
$z[2][4]['name']="cfg_indexurl";
$z[3]=Array("global","",343,375);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",503,530);
$z[4][4]['name']="toubudianhua";
$z[5]=Array("channelartlist","\r\n<li><a class=\"hide\" href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n    <ul>\r\n            {dede:sql sql='Select * from dede_arctype where reid=~id~'}\r\n            <li><a href='[field:typedir function='str_replace(\"{cmspath}\",\"\",@me)'/]'>[field:typename/]</a></li>\r\n            {/dede:sql}\r\n    </ul>\r\n\r\n</li>\r\n",722,1119);
$z[5][4]['typeid']="8";
$z[5][4]['row']="7";

?>