
<field:cn_subject itemname="标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:cn_subject>

<field:cn_name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:cn_name>

<field:cn_email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:cn_email>

<field:cn_tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:cn_tel>

<field:cn_content itemname="内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:cn_content>
