<?php
$z[0]=Array("global","",39,71);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",130,162);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",395,422);
$z[2][4]['name']="cfg_indexurl";
$z[3]=Array("global","",434,466);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",489,515);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",638,665);
$z[5][4]['name']="toubudianhua";
$z[6]=Array("global","",821,848);
$z[6][4]['name']="cfg_indexurl";
$z[7]=Array("global","",856,884);
$z[7][4]['name']="cfg_indexname";
$z[8]=Array("channelartlist","\n<li><a class=\"hide\" href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\n    <ul>\n        \n            \n            {dede:sql sql='Select * from dede_arctype where reid=~id~'}\n            <li><a href='[field:typedir function='str_replace(\"{cmspath}\",\"\",@me)'/]'>[field:typename/]</a></li>\n            {/dede:sql}\n    </ul>\n\n</li>\n",895,1305);
$z[8][4]['typeid']="1";
$z[8][4]['row']="7";

?>