<?php
$z[0]=Array("global","",39,71);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",410,437);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",550,577);
$z[2][4]['name']="cfg_indexurl";
$z[3]=Array("global","",589,621);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",644,670);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",761,788);
$z[5][4]['name']="toubudianhua";
$z[6]=Array("global","",957,984);
$z[6][4]['name']="cfg_indexurl";
$z[7]=Array("global","",992,1020);
$z[7][4]['name']="cfg_indexname";
$z[8]=Array("channelartlist","\r\n<li><a class=\"hide\" href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n    <ul>\r\n        \r\n            \r\n            {dede:sql sql='Select * from dede_arctype where reid=~id~'}\r\n            <li><a href='[field:typedir function='str_replace(\"{cmspath}\",\"\",@me)'/]'>[field:typename/]</a></li>\r\n            {/dede:sql}\r\n    </ul>\r\n\r\n</li>\r\n",1033,1454);
$z[8][4]['typeid']="1";
$z[8][4]['row']="7";

?>