<?php
$z[0]=Array("global","",253,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",322,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",388,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",432,464);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",528,560);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",649,681);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",751,783);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",881,917);
$z[7][4]['filename']="head.html";
$z[8]=Array("channelartlist","\n<li><a href=\"{dede:field name='typeurl'/}\"><b>{dede:field name='typename'/}</b></a>\n{dede:arclist}\n<a href=\"[field:arcurl /]\">[field:title /]</a>\n{/dede:arclist}\n\n</li> \n\n",1249,1475);
$z[8][4]['typeid']="3";
$z[9]=Array("arclist","\n<dd><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></dd>\n",1639,1814);
$z[9][4]['row']="8";
$z[9][4]['titlelen']="28";
$z[9][4]['typeid']="4";
$z[9][4]['orderby']="id";
$z[10]=Array("global","",1985,2006);
$z[10][4]['name']="lianxi";
$z[11]=Array("field","",2155,2184);
$z[11][4]['name']="position";
$z[12]=Array("list"," \n<tr><td class=\"fw_t\" width=\"75%\">·<a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></td><td class=\"fw_s\" width=\"25%\">[[field:pubdate function=\"GetDateTimeMK(@me)\" /]]</td></tr>\n ",2387,2616);
$z[12][4]['pagesize']="10";
$z[13]=Array("pagelist","",3152,3230);
$z[13][4]['listitem']="index,pre,next,end,pageno,option,info";
$z[13][4]['listsize']="2";
$z[14]=Array("include","",3386,3422);
$z[14][4]['filename']="foot.html";

?>